@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJqb2huZG9lIiwiZW1haWwiOiJqb2huLmRvZUBtYWlsLmNvbSIsImV4cCI6MTczODkyOTM5MH0.FPQ6utTEH2bDovupis7sDWn_RwUh7XHSiizT7n0gpWw
@id=742f6277b1c741719e81bb108198f0b6

### HOME
GET  http://localhost:8000/

### LOGIN
POST http://localhost:8000/login
Content-Type: application/json

{
    "email": "john.doe@mail.com",
    "password": "azerty"
}

### GET USERS
GET  http://localhost:8000/users
Authorization: Bearer {{token}}

### GET ONE USER
GET  http://localhost:8000/users/{{id}}
Authorization: Bearer {{token}}

### CREATE ARTICLE
POST http://localhost:8000/articles
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "title": "Article 1",
    "content": "Content of article 1"
}


### GET ARTICLES
GET  http://localhost:8000/articles
Authorization: Bearer {{token}}


